name: Build and push to quay.io
on:
  push:
    branches: [ main ]

env:
  REGISTRY_USER: netobserv+github_ci
  REGISTRY_PASSWORD: ${{ secrets.QUAY_SECRET }}
  REGISTRY: quay.io/netobserv
  REG_IMAGE: network-observability-console-plugin
  REG_TAG: main

jobs:
  push-image:
    name: push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
      - name: install make
        run: sudo apt-get install make
      - name: set up go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: checkout
        uses: actions/checkout@v3
      - name: build images
        run: BASE_IMAGE="${{ env.REGISTRY }}/${{ env.REG_IMAGE }}" TAG="${{ env.REG_TAG }}" make build-ci-images
      - name: podman login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: quay.io
      - name: get short sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.REG_IMAGE }}
          tags: ${{ env.REG_TAG }} ${{ env.short_sha }}
          registry: ${{ env.REGISTRY }}
      - name: print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  codecov-back:
    name: Codecov backend upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v3
    - name: Test
      run: make test-backend
    - name: Report coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: false

  codecov-front:
    name: Codecov frontend upload
    runs-on: ubuntu-latest
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: checkout
      uses: actions/checkout@v3
    - name: Test
      run: make install-frontend test-frontend
    - name: Report coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./web/coverage/cobertura-coverage.xml
        flags: uitests
        fail_ci_if_error: false
